spring.application.name=BasicSpringMVC
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
server.port=8989
#database  jdbc:oracle:thin:@//10.10.196.37:1521/testdev1
spring.datasource.url=jdbc:oracle:thin:@//10.10.196.37:1521/testdev1
spring.datasource.username=DEVP_SOLAR
spring.datasource.password=DEVP_SOLAR